'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class document
    Public Property id As Integer
    Public Property documentname As String
    Public Property extension As String
    Public Property size As Nullable(Of Double)
    Public Property uploaddate As Nullable(Of Date)
    Public Property senddate As Nullable(Of Date)
    Public Property sender As String
    Public Property uploader As String
    Public Property sendstatus As String

End Class
